In [32]:
import gym
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Games
games = ["AirRaid","Alien","Amidar","Assault","Asterix","Asteroids",
         "Atlantis","BankHeist","BattleZone","BeamRider","Berzerk",
         "Bowling","Boxing","Breakout","Carnival","Centipede",
         "ChopperCommand","CrazyClimber","DemonAttack","DoubleDunk",
         "ElevatorAction","Enduro","FishingDerby","Freeway",
         "Frostbite","Gopher","Gravitar","IceHockey","Jamesbond",
         "JourneyEscape","Kangaroo","Krull","KungFuMaster",
         "MontezumaRevenge","MsPacman","NameThisGame","Phoenix",
         "Pitfall","Pong","Pooyan","PrivateEye","Qbert","Riverraid",
         "RoadRunner","Robotank","Seaquest","Skiing","Solaris",
         "SpaceInvaders","StarGunner","Tennis","TimePilot",
         "Tutankham","UpNDown","Venture","VideoPinball","WizardOfWor",
         "YarsRevenge","Zaxxon"]

In [ ]:
# for game in games:
#     env = gym.make(game + "-ram-v0")

In [5]:
env = gym.make("Atlantis-ram-v0")
initobs = env.reset()

In [53]:
dif = np.zeros((128,))
prevobs = env.reset()
for i in range(5):
    obs, reward, done, info = env.step(env.action_space.sample())
    dif += np.abs(obs.astype(int) - initobs.astype(int))
    if done:
        break
dif

array([  300.,     0.,   250.,     0.,   200.,     0.,   150.,     0.,
         100.,     0.,    50.,     0.,     0.,     0.,     5.,     2.,
           0.,     0.,     0.,     0.,     0.,     0.,    24.,    16.,
          24.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
          10.,     0.,     0.,     0.,     0.,     0.,     0.,   512.,
           0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
          33.,   432.,     0.,     0.,     0.,     0.,     0.,     0.,
          36.,   512.,     0.,    97.,     0.,    75.,     0.,     0.,
           0.,     0.,     0.,     0.,   422.,   224.,   168.,     0.,
           0.,     0.,   640.,     0.,     0.,     0.,  1270.,     0.,
           0.,     0.,   112.,     5.,     0.,     0.,     0.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     3.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.,    27.,     0.,     0.,     0.,     0.,     5.,
      

In [40]:
nz2 = np.nonzero(dif)

In [48]:
nz

(array([  0,   2,   4,   6,   8,  10,  14,  15,  22,  23,  24,  32,  39,
         48,  49,  56,  57,  59,  61,  68,  69,  70,  74,  78,  82,  83,
         94, 106, 111, 112, 116, 119, 121, 122]),)

In [52]:
len(nz2[0])

54

In [27]:
obs.astype(int) - initobs.astype(int)

array([ -60,    0,  -50,    0,  -40,    0,  -30,    0,  -20,    0,  -10,
          0,    0,    0,    1,   -1,    0,    0,    0,    0,    0,    0,
          8,    0,    8,    0,    0,    0,    0,    0,    0,    0,   -2,
          0,    0,    0,    0,    0,    0,  110,    0,    0,    0,    0,
          0,    0,    0,    0,    7,  144,    0,    0,    0,    0,    0,
          0,    8, -128,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,  140,   46,    0,    0,    0,    0, -128,    0,    0,
          0,  254,    0,    0,    0,  -16,    1,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,   -1, -246,    0,    0,    0,   10,    0,    0,    1,    0,
          1,    4,    0,    0,    0,    0,    0])

In [ ]:
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
#         print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        break
        if reward != 0.0:
            print reward, info
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break